env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  unicorn/prevent-abbreviations: off
  unicorn/prefer-top-level-await: off
  unicorn/prefer-module: off
  unicorn/no-array-callback-reference: off
  unicorn/no-null: off
  unicorn/filename-case: off
plugins:
  - '@typescript-eslint'
overrides:
  - files:
      - './app/**/*'
    extends:
      - 'plugin:react/recommended'
      - 'plugin:react/jsx-runtime'
      - '@electron-toolkit/eslint-config-ts/recommended'
    rules:
      '@typescript-eslint/explicit-function-return-type': off
    settings:
      react:
        version: '18.2'
  - files:
      - '**/*.astro'
    extends:
      - 'plugin:astro/recommended'
    rules:
      '@typescript-eslint/no-unused-vars': off
  - files:
      - '**/*.config.{js,ts,mjs,cjs}'
    rules:
      'unicorn/prefer-module': off
