root: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - '@electron-toolkit/eslint-config-ts/recommended'
  - '@electron-toolkit/eslint-config-prettier'
settings:
  react:
   version: detect
rules:
  '@typescript-eslint/explicit-function-return-type': off
