root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:astro/recommended'
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - "@typescript-eslint"
overrides:
  - files: [".eslintrc.{js,cjs}"]
    env:
      node: true
    parserOptions:
      sourceType: script
  - files: ["*.astro"]
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: [".astro"]
