name: Starlight Lint
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21'
      - run: corepack enable
      - run: yarn workspaces focus starlight
      - run: yarn lint --fix
      - run: yarn format
      - run: yarn syncpack format
      - name: Commit files
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "style: lint"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
        with:
          branch: ${{ github.head_ref }}
