name: Starlight Lint
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21'
      - run: corepack enable
      - run: yarn install
      - run: yarn lint --fix
      - run: yarn format
